### ISSUE TITLE
Friendly URLs

### ISSUE THREAD

**Issue by excelerondesigns** [modxcms/Login#101]
So I have discovered in issue that is the result of using the plugin in relation to friendly urls. Basically when they are enable the login snippets are not able to process or function any of the calls, options.

Ex: Login Snippet will not process the loginResourceId property, instead it just multiples the parent alias in the url and tries to redirect on it self.
Profile Snippet will not display data when using Friendly URLs

**Comment by Jako** [comment]
Could you give an example with snippet calls and the used chunks. I can't reproduce this and there would be a big noise if the snippets of the Login package won't work with FURLs enabled.

**Comment by Mark-H** [comment]
>  it just multiples the parent alias in the url and tries to redirect on it self.

This sounds very much like a missing `<base href="[[!++site_url]]">` tag in the header

**Comment by Jako** [comment]
Closing this due to long inactivity. Feel free to reopen it with more details if it is still an issue.
