### ISSUE TITLE
ereg() still causing issues in 1.9.4

### ISSUE THREAD

**Issue by pyrographics** [modxcms/Login#104]
Package states that the following change from issue #86 was made, however checking the code installed using the package, it still uses ereg().  When I attempt to replace loginvalidator.class.php with the current github version it will not verify the email address I enter into the Register form so I reverted it to the old broken (in PHP 7) version.

1.9.4
====================================
- Convert deprecated ereg functions to preg_* [#86]

**Comment by Jako** [comment]
For whatever reason that change was not included in the package. There is 1.9.4-pl2 available now.
