### ISSUE TITLE
ConfirmRegister 404 error in 1.9.4-pl2

### ISSUE THREAD

**Issue by guseinovmg** [modxcms/Login#106]
ConfirmRegister 404 error in 1.9.4 and in 1.9.4-pl2

```
[[!ConfirmRegister? &redirectTo=`3`]]
```

Activation link in email:
```
/index.php?id=20&lp=Mm14MzlzMHk&lu=ZmtsaXRAeWFuZGV4LnJ1
```

MODx v2.5.7, NGINX 1.10, PHP 7.0, Ubuntu 16.04

I have to register users manually.
Downgrade to v1.9.2 or v1.9.1 doesn't solve the problem.

**Comment by guseinovmg** [comment]
By default in MODX settings parametr xhtml_urls is turned on, that's why placeholder [[+logoutUrl]] doesn't work
/index.php?id=17&amp;amp;action=logout&amp;action=logout
If  xhtml_urls is turned off, link is working : 
/index.php?id=17&amp;amp;action=logout&action=logout

it is not problem for me because I use placeholder [[~17? &action=`logout`]],
but maybe it help you solve this issue.

**Comment by Jako** [comment]
Is resource 20 (containing the ConfirmRegister call) published and could be seen by not logged users? Is resource 3 published?

A 404 is not normally not the fault of a snippet.

**Comment by guseinovmg** [comment]
You are right, I did resource id20 accessible for anonymous users then registration start to work. Thanks!
