### ISSUE TITLE
Email Validation Not Functioning

### ISSUE THREAD

**Issue by pyrographics** [modxcms/Login#110]
After #86 was fixed our site's email validation is not working with valid email addresses.  Removing the validation code for email allows the Register form to function again.  I have not attempted to reproduce this on other systems.

**Comment by pyrographics** [comment]
It functions correctly on MODXCloud.  The primary difference I see is it uses PHP 5.6.26, our site uses PHP 7.

**Comment by Jako** [comment]
Which PHP version is running on the server, that does not work with the changes here? https://github.com/Jako/Login/commit/2fc491a4d962a46236e667ff080989a8833c585f

It could be a charset/collation issue.

**Comment by crimsonpixel** [comment]
On the Update Profile the email validation does not appear to function correctly.  I have a valid email already in place and when I attempt to Update the profile I keep getting an error message requesting a valid email....

Remove the validation request and the form updates.  Same issue possibly?

**Comment by pyrographics** [comment]
Server is running PHP 7.0, haven't tried PHP 7.1

**Comment by Jako** [comment]
Could you check, if the patch above fixes your issue?

**Comment by pyrographics** [comment]
Jako, I applied the patch, seems to fix the issue.
