### ISSUE TITLE
isLoggedIn defaul settings

### ISSUE THREAD

**Issue by artsur** [modxcms/Login#127]
In default settings parameter "redirectTo" is written as "redirectto". So it doesn't work.
It should be [[!isLoggedIn? &redirectTo=``]]
Could you please change this parameter in default settings?

**Comment by Jako** [comment]
Fixed with https://github.com/modxcms/Login/commit/d00659e1fb35e8bfe58f60c18f730f369d860c00

Will be published with the next package update.
