### ISSUE TITLE
Packaged version 1.9.7 regresses ereg update fixed in #86

### ISSUE THREAD

**Issue by martinf55** [modxcms/Login#136]
Updated to 1.9.7, and the loginvalidator now fails due to calling deprecated ereg functions. This code was updated to use preg_ for issue #86. Package 1.9.5 contained the fixed code. The committed code still seems ok, so the packaging process is perhaps not releasing up-to-date code.

**Comment by Jako** [comment]
https://github.com/Jako/Login/blob/master/_packages/login-1.9.7-pl.transport.zip and the downloadable package on MODX Extras are both containing the preg_match code committed here: https://github.com/Jako/Login/commit/2fc491a4d962a46236e667ff080989a8833c585f, so closing this as invalid.

**Comment by Jako** [comment]
I just have checked it in one installation. The changes in https://github.com/Jako/Login/commit/2fc491a4d962a46236e667ff080989a8833c585f have been installed with the 1.9.7 package.

**Comment by martinf55** [comment]
Thanks for checking again and sorry for the false report. 

I'm guessing my 1.9.7 package download was corrupted or incomplete and the installer reverted to an earlier package: I admit I was was too much of a rush to check the installation log.

I will check the 1.9.7 upgrade again once current time pressures are over.
