### ISSUE TITLE
Confirmation email contains wrong Base64-encoded password

### ISSUE THREAD

**Issue by sentience** [modxcms/Login#148]
Occasionally I have newly-registered users report that their confirmation email link doesn't work. Today, I finally had one such user send me a copy of their confirmation email, and I discovered something very strange:

![confirmation_password_mismatch](https://user-images.githubusercontent.com/89772/57910278-3d5fed80-78c8-11e9-8fb4-b07851f3d73c.png)

When I Base64-decoded the password in the confirmation link, I found it did not match the password shown in plain text. It looked to me like the password in the link was a MODX-generated random password, whereas the password in plain text was the password that the user had supplied in the Sign Up form.

Any idea how this might this occur?

**Comment by Jako** [comment]
The base64 encoded string is not the real user provided password but a temporary one. The confirmation link will be checked against an entry in `core/cache/registry/login/useractivation/`.

This entry has a ttl. So maybe the entry is not valid anymore or there is a different reason for this.

**Comment by sentience** [comment]
I see! OK, I'll keep seeing if I can pin down the cause.
