### ISSUE TITLE
Add Portuguese language (Also in CrowdIn)

### ISSUE THREAD

**Issue by JANogueira** [modxcms/Login#149]
Hi,

I am willing to help with CrowdIn translation to Portuguese.
Please add it to CrowdIn so I can contribute.

Cheers and thanks

**Comment by Jako** [comment]
There is a pt-br lexicon. Could that be used as a start?

**Comment by JANogueira** [comment]
Thanks.

Just one note regarding pt-pt and pt.br assignments for Modx lexicons:

There is an "orthographic agreement" for all countries with Portuguese as primary native language that is implemented for several years now.
The objective of this agreement is to have all countries writing on the same way.

So this Portuguese translation will be the same for pt-pt and pt-br.

I will try to be as generic as possible trying to avoid expressions that can be typically from Portugal as there are some relevant semantic differences from Portugal and Brazil (as an example).

I'll let you know when the translation is finished.

**Comment by JANogueira** [comment]
100% finished.

**Comment by Jako** [comment]
Thanks!
