### ISSUE TITLE
ConfirmRegister - errorPage

### ISSUE THREAD

**Issue by dancalder** [modxcms/Login#151]
the below function always send back to the home page ($id), not sure why this takes preference over $errorPage parameter.

    public function redirectAfterFailure($id = null) {
        $errorPage = (is_null($id)) ? $this->getProperty('errorPage', false, 'isset') : $id;

**Comment by Jako** [comment]
Maybe the errorPage system setting is pointing to the home page.

**Comment by dancalder** [comment]
yes it is but a different resource id is being passed in the snippet:
[[!ConfirmRegister? &redirectTo=`109` &authenticate=`0` &errorPage=`127`]]

**Comment by Jako** [comment]
I have checked/debugged the code. It works fine here. So I think the resource 127 is not published or not visible for a not logged user.

**Comment by Jako** [comment]
Closed for lack of response.
