### ISSUE TITLE
Break 'login.forgot_password_email_text' out to allow editing

### ISSUE THREAD

**Issue by StevenReid** [modxcms/Login#163]
Hi,
It would be good if the content of the email that gets sent out via the 'login.forgot_password_email_text' value that resides in the forgotpassword.inc.php file could be changed to a template or similar.

At the moment, there is no real allowance for the customisation of this data to include branding etc.
and if you edit the file, it could get overwritten when upgrades are performed.

Thanks

**Comment by Jako** [comment]
You could edit the text in the lexicon. That would not get overwritten during an update.
