### ISSUE TITLE
Не работает отправка Email

### ISSUE THREAD

**Issue by searge-c** [modxcms/Login#172]
Возможно, после обновления 1.9.9 что-то пошло не так с отправкой ссылки-подтверждения регистрации на почту. Никаких писем на почтовые ящики не приходит. При регистрации создаётся новый пользователь, но письмо на его почту не отправляется. Однако, если открыть окно авторизации в админ-панель Modx и попытаться восстановить учётную запись через эту форму - письмо придёт. То есть похоже что не отрабатывает модуль регистрации.

**Comment by Jako** [comment]
> There may be an error sending the registration confirmation link to the email after the 1.9.9 update. Letters are not coming to mailboxes. When registering, a new user is created, but no letter is sent to their email. However, if you open the authorization window in the Modx administration area and try to restore your account using this form, you will receive a letter. That is, it seems that the registration module is not working.

**Comment by Jako** [comment]
The only change in the 1.9.9 code was the switch from the regex email address check to a filter_var email address check in https://github.com/modxcms/Login/commit/2a7e1192a47ed0d5bfa147e7f97fd47d2699a791#diff-135db576dfb91fea837ed0c00b6f4efe6e50379613539770b4465057d9ed455e

Can you check, what's going wrong there?

**Comment by Jako** [comment]
Closed due to lack of response. Please reopen the issue if it is still valid.
