### ISSUE TITLE
UpdateProfile does not preserve updated fields on error

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/Login#29]
Perhaps this is just user error, but it seems that UpdateProfile snippet does not preserve any changed fields when the form submission encounters an error.

For example, if a User enters in all their information, but is missing a required field or fails some other validation, the previously loaded values are loaded alongside the errors, and not the modified values for any changed entries prior to submit.

This is not a good UX, the user is then forced to re-enter all the fields, which can potentially be cumbersome and/or upsetting...

**Comment by pepebe** [comment]
Also still an open issue. Bumb :)

**Comment by Jako** [comment]
Fixed with this: https://github.com/modxcms/Login/pull/73/commits/7a7b35ac1def297e00b9a380aaaa83bd94c9205f

**Comment by Jako** [comment]
1.9.3-rc1 is available in https://github.com/Jako/Login/tree/e4154d89774c1b8a0b2580909fb53caea6be1e70/_packages
