### ISSUE TITLE
Inconsistency in placeholder names

### ISSUE THREAD

**Issue by ambienthack** [modxcms/Login#33]
I've found that there is inconsistency in using 
$modx->toPlaceholders() versus $modx->setPlaceholders()
across controllers, and, as a result, in placeholder names.

E.g.

controllers/web/Register.php @ process()

``` php
           $this->modx->setPlaceholders($this->dictionary->toArray(),$placeholderPrefix);      
```

controllers/web/UpdateProfile.php @ setFieldPlaceholders()

``` php
          $this->modx->toPlaceholders($placeholders,$this->getProperty('placeholderPrefix'));   
```

If **$placeholderPrefix** equals to 'hny.' we get: `[[+hny.field_name]]` for Register & `[[+hny..field_name]]` (two dots) for UpdateProfile

**Comment by Jako** [comment]
Fixed with https://github.com/modxcms/Login/pull/73 (Normalize placeholder prefix usage).

**Comment by Jako** [comment]
1.9.3-rc1 is available in https://github.com/Jako/Login/tree/e4154d89774c1b8a0b2580909fb53caea6be1e70/_packages
