### ISSUE TITLE
%253D%253D breaking confirmation link

### ISSUE THREAD

**Issue by bwente** [modxcms/Login#42]
Sometimes the confirmation link is broken. I can't seem to narrow it down. But the link had a 

confirmation.html?lp=a3dnamZxNjA%253D&lu=ZHJicm9uemVAbWFjLmNvbQ%253D%253D

It looked like the same issue from the forums... Should I make the same change?

http://forums.modx.com/index.php?action=thread&thread=66928&i=1

**Comment by bwente** [comment]
might be the cause of this issue too.

http://forums.modx.com/thread/?thread=75184&page=1

**Comment by gadgetto** [comment]
This issue belongs to [#38]

**Comment by gadgetto** [comment]
Fixed in [#42]. Can be closed.
