### ISSUE TITLE
updateProfile errors and prefix

### ISSUE THREAD

**Issue by pepebe** [modxcms/Login#44]
If I'm using a prefix for updateProfile placeholders, I don't get error messages anymore. 

It doesn't matter if I use &placeholderPrefix=`login` (right) or &placeholderPrefix=`login.` (wrong way to do it).

```
<span class="error">[[+login.error.country]]</span>
```

As soon as I don't use &placeholderPrefix, errors are shown as expected.

**Comment by minagerges** [comment]
#27

**Comment by Jako** [comment]
Should be fixed with #73

**Comment by Jako** [comment]
1.9.3-rc1 is available in https://github.com/Jako/Login/tree/e4154d89774c1b8a0b2580909fb53caea6be1e70/_packages
