### ISSUE TITLE
PHP Error in ConfirmRegister processor

### ISSUE THREAD

**Issue by BobRay** [modxcms/Login#53]
Line 58 of the processor has this code:

     $this->user->_setRaw('cachepwd','');

but the _setRaw() method is protected and for some reason it's not accessible here in some versions of PHP.

Changing it back to:

    $this->user->set('cachepwd','');

should fix it.

**Comment by gadgetto** [comment]
The problem is

`$this->user->set('cachepwd','');`

doesn't work as expected as this generates a hash of an empty value and the cachepwd field isn't emptied.

I did a PR which fixes the problem until the set method in MODX core is fixed:
https://github.com/modxcms/Login/pull/55
