### ISSUE TITLE
[Register] Activation email is not sended

### ISSUE THREAD

**Issue by Sergspm** [modxcms/Login#57]
Hello!

In last project i need to add registering users. Users created successfully, but email activation is not sended because "*mail_err_unset_spec*" error occured `(core/model/modx/mail/modphpmailer.class.php:152 revo 2.2.14)`.

I find this code into Login register processor `(core/components/login/processors/register.php:260)`:

```PHP
/* send either to user's email or a specified activation email */
$activationEmail = $this->controller->getProperty('activationEmail',$this->user->get('email'));
```

But `$this->user` is instance of `modUser` and has no email field.

I think it's a bug and code must be like this:

```PHP
/* send either to user's email or a specified activation email */
$activationEmail = $this->controller->getProperty('activationEmail',$this->profile->get('email'));
```
I'm testing this solution in my project, email sende successfully.
I'm sending pullrequest to fix this bug.

**Comment by theboxer** [comment]
Fixed in 4d2b6f07711a87047dad425fb6be18e1571463ba
