### ISSUE TITLE
ConfirmRegister not working after update to 1.9.1

### ISSUE THREAD

**Issue by funkyduke** [modxcms/Login#58]
After updating Login to 1.9.1 (coming from 1.9.0) ConfirmRegister is not working as it should be. When clicking on the confirmation-link in the e-mail you get a blank page. Yes, the user is created, but is non-active. When turning back to 1.9.0. the confirmation-link is working again.

**Comment by Jako** [comment]
This is the error message triggered: 
```
Call to protected method xPDOObject::_setRaw() from context 'LoginConfirmRegisterController' in /var/www/.../core/components/login/controllers/web/ConfirmRegister.php on line 58
```
