### ISSUE TITLE
Bug: controllers\web\Login.php : line 408

### ISSUE THREAD

**Issue by lokamaya** [modxcms/Login#63]
modx\core\components\login\controllers\web\Login.php : 408) E_STRICT information: Only variables should be assigned by reference

**Comment by Jako** [comment]
The whole method needs some refactoring.

**Comment by Jako** [comment]
Fixed with https://github.com/modxcms/Login/pull/83

**Comment by Jako** [comment]
1.9.3-rc1 is available in https://github.com/Jako/Login/tree/e4154d89774c1b8a0b2580909fb53caea6be1e70/_packages
