### ISSUE TITLE
"password_generated_length" & "password_min_length" BUG

### ISSUE THREAD

**Issue by syberknight** [modxcms/Login#69]
hello,
apparently i've found a bug. 
it's explained @ https://github.com/modxcms/revolution/issues/12996
current workaround @ https://forums.modx.com/thread/100064/forgot-password-length-too-small

hope this helps,
thanks.

**Comment by Jako** [comment]
Does your code here work without the PR on Revo?

**Comment by Jako** [comment]
Fixed with 1.9.7
