### ISSUE TITLE
Change password and validateOldPassword fails with square brackets

### ISSUE THREAD

**Issue by prioritypie** [modxcms/Login#74]
In controllers/web/ChangePassword.php the validate method replaces square brackets in the field values with their html entities. Therefore, if someone uses those characters in their new password it is saved with the entity equivalents and next time they try to log in they can't.

I've worked around it for now with:

```
        $passwordFields = array(
            'fieldConfirmNewPassword' => $this->getProperty('fieldConfirmNewPassword','password_new_confirm'),
            'fieldNewPassword' => $this->getProperty('fieldNewPassword','password_new'),
            'fieldOldPassword' => $this->getProperty('fieldOldPassword','password_old'),
        );

        foreach ($fields as $k => $v) {
            if(!in_array($k,$passwordFields)) {
                $fields[$k] = str_replace(array('[', ']'), array('&#91;', '&#93;'), $v);
            }
        }
```

If the password is set using the manager, and includes square brackets, and validateOldPassword is true, the validation does not pass either as the characters in password_old have been replaced again before they get passed to the `modx->user->passwordMatches` method.

Using Login 1.9.2, MODX 2.5.0

The ChangePassword snippet call being used is:

```
[[!ChangePassword?
    &submitVar=`change-password`
    &placeholderPrefix=`cp.`
    &validateOldPassword=`1`
]]
```

**Comment by Jako** [comment]
1.9.3-rc1 is available in https://github.com/Jako/Login/tree/e4154d89774c1b8a0b2580909fb53caea6be1e70/_packages
