### ISSUE TITLE
loginResourceId & logoutResourceId not working  

### ISSUE THREAD

**Issue by robh76** [modxcms/Login#77]
The loginResourceId & logoutResourceId don't have any effect. Here's my snippet...
```
[[!Login? &tplType=`modChunk` &loginTpl=`loginTpl` &loginResourceId=`22` &logoutResourceId=`23`]]
```

The only way I can make this work is by replacing in the loginTpl...
<input class="returnUrl" type="hidden" name="returnUrl" value="[[+request_uri]]" />
with...
<input class="returnUrl" type="hidden" name="returnUrl" value="[[~22]]" />
which redirects after login to resource 22.

There are a number of people on the Modx forums with this issue (some going back several years) and no resolution. Is this a bug?

Thanks in advance!

**Comment by Jako** [comment]
Those properties only work during a direct login.

You could use the following patch (https://github.com/modxcms/Login/commit/ac1eb4403bab63659505f4516cabfe29bd31365c) and work with loggedinResourceId and loggedoutResourceId snippet properties. They will be added in the next version of Login.

**Comment by Jako** [comment]
1.9.3-rc1 is available in https://github.com/Jako/Login/tree/e4154d89774c1b8a0b2580909fb53caea6be1e70/_packages
